MASTER_PORT=29200 NPROC_PER_NODE=8 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 swift rlhf \
        --rlhf_type grpo \
        --model your_best_sft_ckpt_merged \
        --output_dir yourpath/ckpt_speech/qwen2.5-omni-3b-s2 \
        --dataset label/FT-GRPO/2-GRPO/19la_train.json\
        --val_dataset label/FT-GRPO/2-GRPO/19la_dev.json \
        --system yourpath/prompt/FT-GRPO.txt \
        --gradient_checkpointing_kwargs '{"use_reentrant": false}' \
        --torch_dtype bfloat16 \
        --max_length 768 \
        --dataloader_num_workers 8 \
        --target_modules all-linear \
        --save_strategy epoch \
        --freeze_vit false \
        --freeze_aligner false \
        --freeze_llm false \
        --logging_steps 10 \
        --per_device_train_batch_size 32 \
        --per_device_eval_batch_size 8 \
        --gradient_accumulation_steps 1 \
        --save_total_limit 10 \
        --lazy_tokenize true \
        --weight_decay 0.1 \
        --learning_rate 1e-5 \
        --train_type lora \
        --warmup_ratio 0.05 \
        --num_train_epochs 2 \
        --lora_rank 64 \
        --lora_alpha 16 \
        --deepspeed zero2 \
        --max_completion_length 768 \
        --num_generations 8 \
        --log_completions true \
        --external_plugins yourpath/plugin/plugin.py \
        --reward_funcs external_r1v_acc format ft_reward \
        --reward_weights 1 0.1 0.1